import globals from 'globals';
import pluginJs from '@eslint/js';
import pluginReact from 'eslint-plugin-react';

/** @type {import('eslint').Linter.Config[]} */
export default [
  // Specify the files to lint
  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,tsx}'],
  },

  // Define global variables for the browser environment and node environment
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        Buffer: 'readonly', // Declare 'Buffer' as a global variable
      },
    },
  },

  // Add the recommended configurations for JavaScript and React
  pluginJs.configs.recommended,
  pluginReact.configs.flat.recommended,

  // Add adjustments to the linter rules
  {
    rules: {
      // Enable 'no-unused-vars' warning for unused variables
      'no-unused-vars': ['warn'],
      'no-self-assign': 'off', // Disable 'no-self-assign' rule
      'no-empty': 'off', // Disable 'no-empty' rule
      'no-useless-escape': 'off', // Disable 'no-useless-escape' rule
      '@typescript-eslint/require-await': 'off', // Disable the 'require-await' rule for TypeScript
      'no-constant-condition': 'off', // Disable 'no-constant-condition' rule for generated code
      'no-control-regex': 'off', // Disable 'no-control-regex' rule

      // Add custom rule for disabling errors for generated code
      'no-extra-boolean-cast': 'off', // Disable redundant boolean cast warnings
    },
  },

  // Overrides for files generated by Svelte
  {
    files: ['**/.svelte-kit/**'],
    rules: {
      'no-unused-vars': 'off', // Disable 'no-unused-vars' rule for generated files
    },
  },

  // Optionally configure react version for eslint-plugin-react
  {
    settings: {
      react: {
        version: 'detect', // Automatically detect React version (if React is used)
      },
    },
  },
];
