name: Build and Test Svelte Application

on: 
  push:
    branches:
      - "**"  # Trigger bij elke push naar elke branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Haal de laatste code op
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installeer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Installeer dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Voer het buildproces uit
      - name: Build the Svelte application
        run: npm run build

      # 5. (Optioneel) Voer tests uit
      # - name: Run tests
      #   run: npm test